[package]
name = "manga-bot"
version = "0.1.10-dev"
authors = ["Hentioe <me@bluerain.io>"]
edition = "2018"

[dependencies]
reqwest = "0.9.16"
failure = "0.1.5"
scraper = "0.11.0"
lazy_static = "1.3.0"
tree_magic = "0.2.1"
tera = "0.11.20"
serde_derive = "1.0.84"
serde = "1.0.91"
zip = "0.5.2"
walkdir = "2.2.7"
serde_json = "1.0.39"
regex = "1.1.6"
uuid = "0.7.4"
chrono = "0.4.6"
indicatif = "0.11.0"
encoding_rs = "0.8.17"
url = "1.7.2"
scan_dir = "0.3.3"
